# analisis/utils/mapeos.py

# ── Columnas geográficas presentes en todos los CSVs ───────────────────────

COLUMNAS_GEOGRAFICAS = {
    "CVEGEO":   "clave_municipio",
    "NOM_ENT":  "nombre_estado",
    "NOMGEO":   "nombre_municipio",
}

# ── Población — valores absolutos ──────────────────────────────────────────

MAPEO_POBLACION_ABS = {
    "POB1":   "poblacion_total",
    "POB42":  "poblacion_femenina",
    "POB84":  "poblacion_masculina",
    "POB2":   "poblacion_0_2",
    "POB3":   "poblacion_0_4",
    "POB4":   "poblacion_3_5",
    "POB5":   "poblacion_6_11",
    "POB6":   "poblacion_8_14",
    "POB7":   "poblacion_12_14",
    "POB8":   "poblacion_0_14",
    "POB9":   "poblacion_15_17",
    "POB10":  "poblacion_15_24",
    "POB11":  "poblacion_15_29",
    "POB12":  "poblacion_15_64",
    "POB13":  "poblacion_18_24",
    "POB14":  "poblacion_30_49",
    "POB15":  "poblacion_50_59",
    "POB16":  "poblacion_60_64",
    "POB17":  "poblacion_3_mas",
    "POB18":  "poblacion_5_mas",
    "POB19":  "poblacion_12_mas",
    "POB20":  "poblacion_15_mas",
    "POB21":  "poblacion_18_mas",
    "POB22":  "poblacion_25_mas",
    "POB23":  "poblacion_60_mas",
    "POB24":  "poblacion_65_mas",
    "POB25":  "poblacion_70_mas",
    "POB26":  "poblacion_5_9",
    "POB27":  "poblacion_10_14",
    "POB28":  "poblacion_15_19",
    "POB29":  "poblacion_20_24",
    "POB30":  "poblacion_25_29",
    "POB31":  "poblacion_30_34",
    "POB32":  "poblacion_35_39",
    "POB33":  "poblacion_40_44",
    "POB34":  "poblacion_45_49",
    "POB35":  "poblacion_50_54",
    "POB36":  "poblacion_55_59",
    "POB37":  "poblacion_65_69",
    "POB38":  "poblacion_70_74",
    "POB39":  "poblacion_75_79",
    "POB40":  "poblacion_80_84",
    "POB41":  "poblacion_85_mas",
    "POB43":  "poblacion_femenina_0_2",
    "POB44":  "poblacion_femenina_0_4",
    "POB45":  "poblacion_femenina_3_5",
    "POB46":  "poblacion_femenina_6_11",
    "POB47":  "poblacion_femenina_8_14",
    "POB48":  "poblacion_femenina_12_14",
    "POB49":  "poblacion_femenina_0_14",
    "POB50":  "poblacion_femenina_15_17",
    "POB51":  "poblacion_femenina_15_24",
    "POB52":  "poblacion_femenina_15_29",
    "POB53":  "poblacion_femenina_15_49",
    "POB54":  "poblacion_femenina_15_64",
    "POB55":  "poblacion_femenina_18_24",
    "POB56":  "poblacion_femenina_30_49",
    "POB57":  "poblacion_femenina_50_59",
    "POB58":  "poblacion_femenina_60_64",
    "POB59":  "poblacion_femenina_3_mas",
    "POB60":  "poblacion_femenina_5_mas",
    "POB61":  "poblacion_femenina_12_mas",
    "POB62":  "poblacion_femenina_15_mas",
    "POB63":  "poblacion_femenina_18_mas",
    "POB64":  "poblacion_femenina_25_mas",
    "POB65":  "poblacion_femenina_60_mas",
    "POB66":  "poblacion_femenina_65_mas",
    "POB67":  "poblacion_femenina_70_mas",
    "POB68":  "poblacion_femenina_5_9",
    "POB69":  "poblacion_femenina_10_14",
    "POB70":  "poblacion_femenina_15_19",
    "POB71":  "poblacion_femenina_20_24",
    "POB72":  "poblacion_femenina_25_29",
    "POB73":  "poblacion_femenina_30_34",
    "POB74":  "poblacion_femenina_35_39",
    "POB75":  "poblacion_femenina_40_44",
    "POB76":  "poblacion_femenina_45_49",
    "POB77":  "poblacion_femenina_50_54",
    "POB78":  "poblacion_femenina_55_59",
    "POB79":  "poblacion_femenina_65_69",
    "POB80":  "poblacion_femenina_70_74",
    "POB81":  "poblacion_femenina_75_79",
    "POB82":  "poblacion_femenina_80_84",
    "POB83":  "poblacion_femenina_85_mas",
    "POB85":  "poblacion_masculina_0_2",
    "POB86":  "poblacion_masculina_0_4",
    "POB87":  "poblacion_masculina_3_5",
    "POB88":  "poblacion_masculina_6_11",
    "POB89":  "poblacion_masculina_8_14",
    "POB90":  "poblacion_masculina_12_14",
    "POB91":  "poblacion_masculina_0_14",
    "POB92":  "poblacion_masculina_15_17",
    "POB93":  "poblacion_masculina_15_24",
    "POB94":  "poblacion_masculina_15_29",
    "POB95":  "poblacion_masculina_15_64",
    "POB96":  "poblacion_masculina_18_24",
    "POB97":  "poblacion_masculina_30_49",
    "POB98":  "poblacion_masculina_50_59",
    "POB99":  "poblacion_masculina_60_64",
    "POB100": "poblacion_masculina_3_mas",
    "POB101": "poblacion_masculina_5_mas",
    "POB102": "poblacion_masculina_12_mas",
    "POB103": "poblacion_masculina_15_mas",
    "POB104": "poblacion_masculina_18_mas",
    "POB105": "poblacion_masculina_25_mas",
    "POB106": "poblacion_masculina_60_mas",
    "POB107": "poblacion_masculina_65_mas",
    "POB108": "poblacion_masculina_70_mas",
    "POB109": "poblacion_masculina_5_9",
    "POB110": "poblacion_masculina_10_14",
    "POB111": "poblacion_masculina_15_19",
    "POB112": "poblacion_masculina_20_24",
    "POB113": "poblacion_masculina_25_29",
    "POB114": "poblacion_masculina_30_34",
    "POB115": "poblacion_masculina_35_39",
    "POB116": "poblacion_masculina_40_44",
    "POB117": "poblacion_masculina_45_49",
    "POB118": "poblacion_masculina_50_54",
    "POB119": "poblacion_masculina_55_59",
    "POB120": "poblacion_masculina_65_69",
    "POB121": "poblacion_masculina_70_74",
    "POB122": "poblacion_masculina_75_79",
    "POB123": "poblacion_masculina_80_84",
    "POB124": "poblacion_masculina_85_mas",
}

# ── Población — porcentajes ─────────────────────────────────────────────────

MAPEO_POBLACION_REL = {
    "POB2_R":   "porcentaje_0_2",
    "POB3_R":   "porcentaje_0_4",
    "POB4_R":   "porcentaje_3_5",
    "POB5_R":   "porcentaje_6_11",
    "POB6_R":   "porcentaje_8_14",
    "POB7_R":   "porcentaje_12_14",
    "POB8_R":   "porcentaje_0_14",
    "POB9_R":   "porcentaje_15_17",
    "POB10_R":  "porcentaje_15_24",
    "POB11_R":  "porcentaje_15_29",
    "POB12_R":  "porcentaje_15_64",
    "POB13_R":  "porcentaje_18_24",
    "POB14_R":  "porcentaje_30_49",
    "POB15_R":  "porcentaje_50_59",
    "POB16_R":  "porcentaje_60_64",
    "POB17_R":  "porcentaje_3_mas",
    "POB18_R":  "porcentaje_5_mas",
    "POB19_R":  "porcentaje_12_mas",
    "POB20_R":  "porcentaje_15_mas",
    "POB21_R":  "porcentaje_18_mas",
    "POB22_R":  "porcentaje_25_mas",
    "POB23_R":  "porcentaje_60_mas",
    "POB24_R":  "porcentaje_65_mas",
    "POB25_R":  "porcentaje_70_mas",
    "POB26_R":  "porcentaje_5_9",
    "POB27_R":  "porcentaje_10_14",
    "POB28_R":  "porcentaje_15_19",
    "POB29_R":  "porcentaje_20_24",
    "POB30_R":  "porcentaje_25_29",
    "POB31_R":  "porcentaje_30_34",
    "POB32_R":  "porcentaje_35_39",
    "POB33_R":  "porcentaje_40_44",
    "POB34_R":  "porcentaje_45_49",
    "POB35_R":  "porcentaje_50_54",
    "POB36_R":  "porcentaje_55_59",
    "POB37_R":  "porcentaje_65_69",
    "POB38_R":  "porcentaje_70_74",
    "POB39_R":  "porcentaje_75_79",
    "POB40_R":  "porcentaje_80_84",
    "POB41_R":  "porcentaje_85_mas",
    "POB42_R":  "porcentaje_femenino",
    "POB84_R":  "porcentaje_masculino",
    "POB125_R": "relacion_hombres_mujeres",
    "POB126_R": "razon_dependencia_total",
    "POB127_R": "razon_dependencia_infantil",
    "POB128_R": "razon_dependencia_vejez",
    "POB129_R": "edad_mediana_total",
    "POB130_R": "edad_mediana_femenina",
    "POB131_R": "edad_mediana_masculina",
    "POB132_R": "indice_envejecimiento_total",
    "POB133_R": "indice_envejecimiento_femenino",
    "POB134_R": "indice_envejecimiento_masculino",
    "POB43_R":  "porcentaje_femenino_0_2",
    "POB44_R":  "porcentaje_femenino_0_4",
    "POB45_R":  "porcentaje_femenino_3_5",
    "POB46_R":  "porcentaje_femenino_6_11",
    "POB47_R":  "porcentaje_femenino_8_14",
    "POB48_R":  "porcentaje_femenino_12_14",
    "POB49_R":  "porcentaje_femenino_0_14",
    "POB50_R":  "porcentaje_femenino_15_17",
    "POB51_R":  "porcentaje_femenino_15_24",
    "POB52_R":  "porcentaje_femenino_15_29",
    "POB53_R":  "porcentaje_femenino_15_49",
    "POB54_R":  "porcentaje_femenino_15_64",
    "POB55_R":  "porcentaje_femenino_18_24",
    "POB56_R":  "porcentaje_femenino_30_49",
    "POB57_R":  "porcentaje_femenino_50_59",
    "POB58_R":  "porcentaje_femenino_60_64",
    "POB59_R":  "porcentaje_femenino_3_mas",
    "POB60_R":  "porcentaje_femenino_5_mas",
    "POB61_R":  "porcentaje_femenino_12_mas",
    "POB62_R":  "porcentaje_femenino_15_mas",
    "POB63_R":  "porcentaje_femenino_18_mas",
    "POB64_R":  "porcentaje_femenino_25_mas",
    "POB65_R":  "porcentaje_femenino_60_mas",
    "POB66_R":  "porcentaje_femenino_65_mas",
    "POB67_R":  "porcentaje_femenino_70_mas",
    "POB68_R":  "porcentaje_femenino_5_9",
    "POB69_R":  "porcentaje_femenino_10_14",
    "POB70_R":  "porcentaje_femenino_15_19",
    "POB71_R":  "porcentaje_femenino_20_24",
    "POB72_R":  "porcentaje_femenino_25_29",
    "POB73_R":  "porcentaje_femenino_30_34",
    "POB74_R":  "porcentaje_femenino_35_39",
    "POB75_R":  "porcentaje_femenino_40_44",
    "POB76_R":  "porcentaje_femenino_45_49",
    "POB77_R":  "porcentaje_femenino_50_54",
    "POB78_R":  "porcentaje_femenino_55_59",
    "POB79_R":  "porcentaje_femenino_65_69",
    "POB80_R":  "porcentaje_femenino_70_74",
    "POB81_R":  "porcentaje_femenino_75_79",
    "POB82_R":  "porcentaje_femenino_80_84",
    "POB83_R":  "porcentaje_femenino_85_mas",
    "POB85_R":  "porcentaje_masculino_0_2",
    "POB86_R":  "porcentaje_masculino_0_4",
    "POB87_R":  "porcentaje_masculino_3_5",
    "POB88_R":  "porcentaje_masculino_6_11",
    "POB89_R":  "porcentaje_masculino_8_14",
    "POB90_R":  "porcentaje_masculino_12_14",
    "POB91_R":  "porcentaje_masculino_0_14",
    "POB92_R":  "porcentaje_masculino_15_17",
    "POB93_R":  "porcentaje_masculino_15_24",
    "POB94_R":  "porcentaje_masculino_15_29",
    "POB95_R":  "porcentaje_masculino_15_64",
    "POB96_R":  "porcentaje_masculino_18_24",
    "POB97_R":  "porcentaje_masculino_30_49",
    "POB98_R":  "porcentaje_masculino_50_59",
    "POB99_R":  "porcentaje_masculino_60_64",
    "POB100_R": "porcentaje_masculino_3_mas",
    "POB101_R": "porcentaje_masculino_5_mas",
    "POB102_R": "porcentaje_masculino_12_mas",
    "POB103_R": "porcentaje_masculino_15_mas",
    "POB104_R": "porcentaje_masculino_18_mas",
    "POB105_R": "porcentaje_masculino_25_mas",
    "POB106_R": "porcentaje_masculino_60_mas",
    "POB107_R": "porcentaje_masculino_65_mas",
    "POB108_R": "porcentaje_masculino_70_mas",
    "POB109_R": "porcentaje_masculino_5_9",
    "POB110_R": "porcentaje_masculino_10_14",
    "POB111_R": "porcentaje_masculino_15_19",
    "POB112_R": "porcentaje_masculino_20_24",
    "POB113_R": "porcentaje_masculino_25_29",
    "POB114_R": "porcentaje_masculino_30_34",
    "POB115_R": "porcentaje_masculino_35_39",
    "POB116_R": "porcentaje_masculino_40_44",
    "POB117_R": "porcentaje_masculino_45_49",
    "POB118_R": "porcentaje_masculino_50_54",
    "POB119_R": "porcentaje_masculino_55_59",
    "POB120_R": "porcentaje_masculino_65_69",
    "POB121_R": "porcentaje_masculino_70_74",
    "POB122_R": "porcentaje_masculino_75_79",
    "POB123_R": "porcentaje_masculino_80_84",
    "POB124_R": "porcentaje_masculino_85_mas",
}

# ── Económicas — valores absolutos ─────────────────────────────────────────

MAPEO_ECONOMICAS_ABS = {
    "ECO1":  "pea_12_mas",
    "ECO2":  "pea_femenina_12_mas",
    "ECO3":  "pea_masculina_12_mas",
    "ECO4":  "ocupados_12_mas",
    "ECO5":  "ocupadas_femeninas_12_mas",
    "ECO6":  "ocupados_masculinos_12_mas",
    "ECO7":  "ocupados_sin_escolaridad",
    "ECO8":  "ocupadas_sin_escolaridad",
    "ECO9":  "ocupados_sin_escolaridad_masculinos",
    "ECO10": "ocupados_primaria_aprobada",
    "ECO11": "ocupadas_primaria_aprobada",
    "ECO12": "ocupados_primaria_aprobada_masculinos",
    "ECO13": "ocupados_secundaria_incompleta",
    "ECO14": "ocupadas_secundaria_incompleta",
    "ECO15": "ocupados_secundaria_incompleta_masculinos",
    "ECO16": "ocupados_secundaria_completa",
    "ECO17": "ocupadas_secundaria_completa",
    "ECO18": "ocupados_secundaria_completa_masculinos",
    "ECO19": "ocupados_media_superior_aprobada",
    "ECO20": "ocupadas_media_superior_aprobada",
    "ECO21": "ocupados_media_superior_aprobada_masculinos",
    "ECO22": "ocupados_superior_posgrado",
    "ECO23": "ocupadas_superior_posgrado",
    "ECO24": "ocupados_superior_posgrado_masculinos",
    "ECO25": "desocupados_12_mas",
    "ECO26": "desocupadas_femeninas_12_mas",
    "ECO27": "desocupados_masculinos_12_mas",
    "ECO28": "no_pea_12_mas",
    "ECO29": "no_pea_femenina_12_mas",
    "ECO30": "no_pea_masculina_12_mas",
    "ECO31": "no_pea_pensionados_jubilados",
    "ECO32": "no_pea_pensionadas_jubiladas",
    "ECO33": "no_pea_pensionados_jubilados_masculinos",
    "ECO34": "no_pea_estudiantes",
    "ECO35": "no_pea_estudiantes_femeninas",
    "ECO36": "no_pea_estudiantes_masculinos",
    "ECO37": "no_pea_quehaceres_hogar",
    "ECO38": "no_pea_quehaceres_hogar_femeninas",
    "ECO39": "no_pea_quehaceres_hogar_masculinos",
    "ECO40": "no_pea_discapacidad",
    "ECO41": "no_pea_discapacidad_femeninas",
    "ECO42": "no_pea_discapacidad_masculinos",
    "ECO43": "no_pea_otra_razon",
    "ECO44": "no_pea_otra_razon_femeninas",
    "ECO45": "no_pea_otra_razon_masculinos",
}

# ── Económicas — porcentajes ────────────────────────────────────────────────

MAPEO_ECONOMICAS_REL = {
    "ECO1_R":  "porcentaje_pea_12_mas",
    "ECO2_R":  "porcentaje_pea_femenina_12_mas",
    "ECO3_R":  "porcentaje_pea_masculina_12_mas",
    "ECO4_R":  "porcentaje_ocupados_12_mas",
    "ECO5_R":  "porcentaje_ocupadas_femeninas_12_mas",
    "ECO6_R":  "porcentaje_ocupados_masculinos_12_mas",
    "ECO7_R":  "porcentaje_ocupados_sin_escolaridad",
    "ECO8_R":  "porcentaje_ocupadas_sin_escolaridad",
    "ECO9_R":  "porcentaje_ocupados_sin_escolaridad_masculinos",
    "ECO10_R": "porcentaje_ocupados_primaria",
    "ECO11_R": "porcentaje_ocupadas_primaria",
    "ECO12_R": "porcentaje_ocupados_primaria_masculinos",
    "ECO13_R": "porcentaje_ocupados_secundaria_incompleta",
    "ECO14_R": "porcentaje_ocupadas_secundaria_incompleta",
    "ECO15_R": "porcentaje_ocupados_secundaria_incompleta_masculinos",
    "ECO16_R": "porcentaje_ocupados_secundaria_completa",
    "ECO17_R": "porcentaje_ocupadas_secundaria_completa",
    "ECO18_R": "porcentaje_ocupados_secundaria_completa_masculinos",
    "ECO19_R": "porcentaje_ocupados_media_superior",
    "ECO20_R": "porcentaje_ocupadas_media_superior",
    "ECO21_R": "porcentaje_ocupados_media_superior_masculinos",
    "ECO22_R": "porcentaje_ocupados_superior_posgrado",
    "ECO23_R": "porcentaje_ocupadas_superior_posgrado",
    "ECO24_R": "porcentaje_ocupados_superior_posgrado_masculinos",
    "ECO25_R": "porcentaje_desocupados_12_mas",
    "ECO26_R": "porcentaje_desocupadas_femeninas_12_mas",
    "ECO27_R": "porcentaje_desocupados_masculinos_12_mas",
    "ECO28_R": "porcentaje_no_pea_12_mas",
    "ECO29_R": "porcentaje_no_pea_femenina_12_mas",
    "ECO30_R": "porcentaje_no_pea_masculina_12_mas",
    "ECO31_R": "porcentaje_no_pea_pensionados",
    "ECO32_R": "porcentaje_no_pea_pensionadas",
    "ECO33_R": "porcentaje_no_pea_pensionados_masculinos",
    "ECO34_R": "porcentaje_no_pea_estudiantes",
    "ECO35_R": "porcentaje_no_pea_estudiantes_femeninas",
    "ECO36_R": "porcentaje_no_pea_estudiantes_masculinos",
    "ECO37_R": "porcentaje_no_pea_quehaceres_hogar",
    "ECO38_R": "porcentaje_no_pea_quehaceres_hogar_femeninas",
    "ECO39_R": "porcentaje_no_pea_quehaceres_hogar_masculinos",
    "ECO40_R": "porcentaje_no_pea_discapacidad",
    "ECO41_R": "porcentaje_no_pea_discapacidad_femeninas",
    "ECO42_R": "porcentaje_no_pea_discapacidad_masculinos",
    "ECO43_R": "porcentaje_no_pea_otra_razon",
    "ECO44_R": "porcentaje_no_pea_otra_razon_femeninas",
    "ECO45_R": "porcentaje_no_pea_otra_razon_masculinos",
}

# ── Salud — porcentajes ─────────────────────────────────────────────────────

MAPEO_SALUD_REL = {
    "SALUD1_R":  "porcentaje_afiliacion_servicios_salud",
    "SALUD2_R":  "porcentaje_sin_afiliacion",
    "SALUD3_R":  "porcentaje_afiliacion_imss",
    "SALUD10_R": "porcentaje_afiliacion_imss_bienestar",
    "SALUD4_R":  "porcentaje_afiliacion_issste",
    "SALUD9_R":  "porcentaje_afiliacion_issste_estatal",
    "SALUD5_R":  "porcentaje_afiliacion_insabi",
    "SALUD6_R":  "porcentaje_afiliacion_pemex_defensa_marina",
    "SALUD7_R":  "porcentaje_afiliacion_privada",
    "SALUD8_R":  "porcentaje_afiliacion_otra",
}

# ── Salud — valores absolutos ───────────────────────────────────────────────
# El SCINCE publica salud principalmente como porcentajes.
# SaludABS usa las mismas claves _R; se carga con MAPEO_SALUD_REL.
MAPEO_SALUD_ABS = MAPEO_SALUD_REL


# ── Función de normalización ────────────────────────────────────────────────

def normalizar_csv(df, tema: str, tipo: str = "absoluto"):
    """
    Renombra columnas de un DataFrame según tema y tipo.

    Args:
        df:    DataFrame cargado desde CSV del SCINCE
        tema:  "poblacion" | "economicas" | "salud"
        tipo:  "absoluto"  | "relativo"
    """
    if tema == "poblacion":
        mapeo = MAPEO_POBLACION_ABS if tipo == "absoluto" else MAPEO_POBLACION_REL
    elif tema == "economicas":
        mapeo = MAPEO_ECONOMICAS_ABS if tipo == "absoluto" else MAPEO_ECONOMICAS_REL
    elif tema == "salud":
        mapeo = MAPEO_SALUD_REL
    else:
        raise ValueError(f"Tema no reconocido: {tema}")

    cols = {k: v for k, v in mapeo.items() if k in df.columns}
    if cols:
        df = df.rename(columns=cols)
        print(f"  Renombradas {len(cols)} columnas ({tema}/{tipo})")

    if "clave_municipio" in df.columns:
        df["clave_estado"] = df["clave_municipio"].astype(str).str[:2]

    return df